import textwrap
from typing import Any, Dict

SYSTEM_DISCLAIMER = textwrap.dedent(
    """
    IMPORTANT DISCLAIMER - HUMAN OVERSIGHT REQUIRED

    This Academic Agentic Review Intelligence System (AARIS) is an AI-powered tool designed to ASSIST, not REPLACE, human academic reviewers.

    ⚠️ CRITICAL LIMITATIONS:
    • AI-generated reviews are preliminary assessments only
    • Human expert review is MANDATORY before any publication decisions
    • AI may miss nuanced academic context, cultural considerations, or emerging research
    • Technical limitations may affect accuracy of domain-specific evaluations

    📋 RECOMMENDED WORKFLOW:
    1. Use AARIS for initial screening and comprehensive analysis
    2. Human experts must review, validate, and refine all AI recommendations
    3. Final editorial decisions should always involve qualified human reviewers
    4. Consider AI output as one input among many in the review process

    🎯 INTENDED USE:
    • Accelerate initial review processes
    • Identify potential issues for human reviewer attention
    • Provide structured analysis framework
    • Support consistency in review criteria

    ❌ NOT INTENDED FOR:
    • Autonomous publication decisions
    • Replacement of peer review process
    • Final acceptance/rejection determinations
    • Sensitive or controversial research areas without human oversight

    By using this system, you acknowledge that human expertise remains essential for fair, accurate, and ethical academic review processes.
    """
).strip()

PDF_DISCLAIMER = textwrap.dedent(
    """
    DISCLAIMER: This review was generated by an AI system and requires human validation before any editorial decisions.
    Human expert review is mandatory for fair and accurate academic assessment.
    """
).strip()

API_DISCLAIMER: Dict[str, Any] = {
    "disclaimer": "AI-generated review requires human oversight",
    "human_review_required": True,
    "intended_use": "preliminary_assessment_only",
    "warning": "Do not use for final publication decisions without human expert validation",
}


class DisclaimerService:
    """Service providing consistent disclaimer text for different outputs."""

    @staticmethod
    def get_system_disclaimer() -> str:
        """Return the full system disclaimer used in interactive UI or logs."""
        return SYSTEM_DISCLAIMER

    @staticmethod
    def get_pdf_disclaimer() -> str:
        """Return a short disclaimer suitable for inclusion in generated PDFs."""
        return PDF_DISCLAIMER

    @staticmethod
    def get_api_disclaimer() -> Dict[str, Any]:
        """Return a structured disclaimer suitable for API responses."""
        return API_DISCLAIMER.copy()


disclaimer_service = DisclaimerService()
