from datetime import datetime
from io import BytesIO
from typing import Any, Dict

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


class PDFGenerator:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()

    def _setup_custom_styles(self):
        self.styles.add(
            ParagraphStyle(
                name="CustomTitle",
                parent=self.styles["Heading1"],
                fontSize=18,
                spaceAfter=30,
                textColor=colors.darkblue,
                alignment=1,  # Center
            )
        )

        self.styles.add(
            ParagraphStyle(
                name="SectionHeader",
                parent=self.styles["Heading2"],
                fontSize=14,
                spaceBefore=20,
                spaceAfter=10,
                textColor=colors.darkblue,
            )
        )

        self.styles.add(
            ParagraphStyle(
                name="Highlight",
                parent=self.styles["Normal"],
                backColor=colors.yellow,
                borderColor=colors.orange,
                borderWidth=1,
                borderPadding=5,
            )
        )

    def generate_review_pdf(self, submission: Dict[str, Any], report: str) -> BytesIO:
        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=18,
        )

        story = []

        # Header
        story.append(
            Paragraph("ACADEMIC JOURNAL REVIEW REPORT", self.styles["CustomTitle"])
        )
        story.append(Spacer(1, 20))

        # Manuscript info table
        manuscript_data = [
            ["Manuscript Title:", submission.get("title", "N/A")],
            ["Review Date:", datetime.now().strftime("%B %d, %Y")],
            ["Status:", submission.get("status", "N/A").upper()],
            ["Pages:", str(submission.get("file_metadata", {}).get("pages", "N/A"))],
        ]

        manuscript_table = Table(manuscript_data, colWidths=[2 * inch, 4 * inch])
        manuscript_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
                    ("TEXTCOLOR", (0, 0), (-1, -1), colors.black),
                    ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                    ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                    ("FONTSIZE", (0, 0), (-1, -1), 10),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
                    ("BACKGROUND", (1, 0), (1, -1), colors.beige),
                    ("GRID", (0, 0), (-1, -1), 1, colors.black),
                ]
            )
        )

        story.append(manuscript_table)
        story.append(Spacer(1, 30))

        # Process report content
        if not report or report.strip() == "":
            story.append(
                Paragraph("Report generation in progress...", self.styles["Normal"])
            )
        else:
            # Clean and process markdown content
            lines = report.split("\n")
            for line in lines:
                line = line.strip()
                if not line:
                    story.append(Spacer(1, 6))
                elif line.startswith("# "):
                    story.append(Paragraph(line[2:], self.styles["SectionHeader"]))
                elif line.startswith("## "):
                    story.append(Paragraph(line[3:], self.styles["SectionHeader"]))
                elif line.startswith("- "):
                    story.append(Paragraph(line, self.styles["Normal"]))
                elif "**" in line:
                    formatted_line = line.replace("**", "<b>").replace("**", "</b>")
                    story.append(Paragraph(formatted_line, self.styles["Normal"]))
                else:
                    story.append(Paragraph(line, self.styles["Normal"]))
                story.append(Spacer(1, 4))

        # Footer
        story.append(Spacer(1, 30))
        footer_data = [
            ["Generated by:", "AARIS - Academic AI Review System"],
            ["Report ID:", submission.get("id", "N/A")],
            ["Generated on:", datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")],
        ]

        footer_table = Table(footer_data, colWidths=[2 * inch, 4 * inch])
        footer_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), colors.lightgrey),
                    ("TEXTCOLOR", (0, 0), (-1, -1), colors.black),
                    ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                    ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("GRID", (0, 0), (-1, -1), 1, colors.black),
                ]
            )
        )

        story.append(footer_table)

        doc.build(story)
        buffer.seek(0)
        return buffer


pdf_generator = PDFGenerator()
